blank_issues_enabled: false

contact_links:
  - name: ğŸ’¬ General questions (å¯»æ±‚å¸®åŠ©)
    url: https://github.com/InternLM/InternLM/discussions
    about: Ask general usage questions and discuss with other InternLM community members
  - name: ğŸŒ Explore InternLM (å®˜ç½‘)
    url: https://internlm.org/
    about: Get know more about InternLM
